### ISSUE TITLE
Annotation file

### ISSUE THREAD

**Issue by yz3n18** [qinghezeng/ABRS-P#1]
Hi,
Thank you for providing all these amazing tools for analysing liver whole image slides. They have been incredibly inspiring. I have followed your tutorial smoothly, but I am a little bit confused about the annotation file.

As you mentioned in your paper, the model trained on manually annotated tumour regions outperformed the model generated from the whole tissue. May i ask what the annotation file looks like and is it available for you to provide an example of it?

Thank you in advance!

**Comment by qinghezeng** [comment]
Hi!
Thank you very much for your interest and the question! The manual annotations are coarse polygon ROIs of tumor regions. Please find below an example and hope it helps. 

![image](https://github.com/qinghezeng/ABRS-P/assets/22932036/8a24e61e-4e14-43a4-921a-c0484ddab87a)

Pixel-level manual annotations or tumor masks detected by a trained deep learning model may provide even better results.

**Comment by yz3n18** [comment]
Hi,
Thank you for your answer! I will try both methods to identify tumor regions.
Additionally, I wanted to bring to your attention that there are missing commas in main.py at line 129 and create_splits_seq.py at line 19 in the Histo2GeneSignatures repository. All other codes could be conveniently reproduced!

**Comment by qinghezeng** [comment]
Hi!

Sounds great and looking forward to the results!

Thank you very much for pointing that out. I accidentally deleted the commas when I was cleaning the code for some experiments related to other projects. They are now corrected. Thanks again for giving our code a try!

Best,
Qinghe
